In [6]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import warnings

In [3]:
df= pd.read_csv('used_cars_messy.csv')
df.head()

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,2581,Renault Duster,Renault,Duster,7,67647,Dealer,Diesel,Manual,19.87,1461.0,83.80,5.0,575000.0
1,224,Maruti Wagon R,Maruti,Wagon R,3,52000,Dealer,CNG,Manual,33.54,998.0,67.04,5.0,435000.0
2,1803,Honda City,Honda,City,3,48959,Dealer,Petrol,Manual,NaN,1497.0,117.60,5.0,875000.0
3,2728,Mahindra Scorpio,Mahindra,Scorpio,6,82000,dealer,Diesel,Manual,15.4,2179.0,NaN,8.0,925000.0
4,14160,Mahindra XUV500,Mahindra,XUV500,4,34000,Dealer,Diesel,Automatic,16.0,2179.0,140.00,7.0,1175000.0

In [8]:
df.shape

(15661, 14)

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15661 entries, 0 to 15660
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         15661 non-null  int64
 1   car_name           15661 non-null  str
 2   brand              15661 non-null  str
 3   model              15661 non-null  str
 4   vehicle_age        15661 non-null  int64
 5   km_driven          15661 non-null  str
 6   seller_type        15661 non-null  str
 7   fuel_type          15661 non-null  str
 8   transmission_type  15661 non-null  str
 9   mileage            14376 non-null  str
 10  engine             13792 non-null  float64
 11  max_power          14862 non-null  float64
 12  seats              15218 non-null  float64
 13  selling_price      15503 non-null  float64
dtypes: float64(4), int64(2), str(8)
memory usage: 1.7 MB

In [10]:
df.describe()

,Unnamed: 0,vehicle_age,engine,max_power,seats,selling_price
count,15661.000000,15661.000000,13792.000000,14862.000000,15218.000000,1.550300e+04
mean,9808.189643,6.036843,1480.489342,100.513582,5.324418,1.032764e+06
std,5642.981540,3.015072,511.446057,42.854632,0.805993,1.607380e+07
min,0.000000,0.000000,793.000000,38.400000,0.000000,5.000000e+02
25%,4901.000000,4.000000,1197.000000,74.000000,5.000000,3.850000e+05
50%,9858.000000,6.000000,1248.000000,88.500000,5.000000,5.550000e+05
75%,14666.000000,8.000000,1582.000000,117.300000,5.000000,8.250000e+05
max,19543.000000,29.000000,6592.000000,626.000000,9.000000,1.000000e+09

In [11]:
df.isnull().sum()

Unnamed: 0              0
car_name                0
brand                   0
model                   0
vehicle_age             0
km_driven               0
seller_type             0
fuel_type               0
transmission_type       0
mileage              1285
engine               1869
max_power             799
seats                 443
selling_price         158
dtype: int64

In [12]:
df.isnull().sum() * 100 / len(df)

Unnamed: 0            0.000000
car_name              0.000000
brand                 0.000000
model                 0.000000
vehicle_age           0.000000
km_driven             0.000000
seller_type           0.000000
fuel_type             0.000000
transmission_type     0.000000
mileage               8.205095
engine               11.934104
max_power             5.101845
seats                 2.828683
selling_price         1.008876
dtype: float64

Task 2 — Clean the Data

In [13]:
df.duplicated().sum()

np.int64(169)

In [14]:
df[df.duplicated(keep=False)].sort_values('car_name')

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
9347,1210,Audi A4,Audi,A4,9,23994,Dealer,Diesel,Automatic,17.11,NaN,174.33,5.0,1275000.0
5920,1210,Audi A4,Audi,A4,9,23994,Dealer,Diesel,Automatic,17.11,NaN,174.33,5.0,1275000.0
13398,6871,Audi A4,Audi,A4,4,53700,Individual,Diesel,Automatic,18.25,1968.0,187.74,5.0,1760000.0
3642,6871,Audi A4,Audi,A4,4,53700,Individual,Diesel,Automatic,18.25,1968.0,187.74,5.0,1760000.0
867,16053,BMW 6,BMW,6,3,11000,Dealer,Diesel,Automatic,17.09,2993.0,NaN,4.0,5600000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4727,1809,Volkswagen Vento,Volkswagen,Vento,7,59000,Dealer,Petrol,Manual,15.04,1598.0,103.60,5.0,450000.0
9546,7646,Volkswagen Vento,Volkswagen,Vento,7,32000,Dealer,Diesel,Manual,NaN,1498.0,103.20,5.0,725000.0
10280,7646,Volkswagen Vento,Volkswagen,Vento,7,32000,Dealer,Diesel,Manual,NaN,1498.0,103.20,5.0,725000.0
911,18223,Volkswagen Vento,Volkswagen,Vento,10,69988,Dealer,Diesel,Manual,20.54,1598.0,103.60,5.0,349000.0
7791,1809,Volkswagen Vento,Volkswagen,Vento,7,59000,Dealer,Petrol,Manual,15.04,1598.0,103.60,5.0,450000.0

In [19]:
df=df.dropna(subset=['selling_price'])
df.shape

(15503, 14)

In [23]:
df['brand'] = df['brand'].str.strip().str.lower()
df['model'] = df['model'].str.strip().str.lower()
df['car_name'] = df['car_name'].str.strip().str.lower()

In [29]:
df['mileage'] = df['mileage'].astype(str).str.extract('(\\d+\\.?\\d*)').astype(float)
df.head()

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,2581,renault duster,renault,duster,7,67647,Dealer,Diesel,Manual,19.87,1461.0,83.80,5.0,575000.0
1,224,maruti wagon r,maruti,wagon r,3,52000,Dealer,CNG,Manual,33.54,998.0,67.04,5.0,435000.0
2,1803,honda city,honda,city,3,48959,Dealer,Petrol,Manual,NaN,1497.0,117.60,5.0,875000.0
3,2728,mahindra scorpio,mahindra,scorpio,6,82000,dealer,Diesel,Manual,15.40,2179.0,NaN,8.0,925000.0
4,14160,mahindra xuv500,mahindra,xuv500,4,34000,Dealer,Diesel,Automatic,16.00,2179.0,140.00,7.0,1175000.0

In [41]:
df['engine'] = df['engine'].astype(str).str.extract('(\\d+)').astype(float)

In [42]:
df['max_power'] = df['max_power'].astype(str).str.extract('(\\d+\\.?\\d*)').astype(float)

In [43]:
num_cols = ['mileage', 'engine', 'max_power', 'seats']

for col in num_cols:
    df[col].fillna(df[col].median(), inplace=True)

C:\Users\venka\AppData\Local\Temp\ipykernel_14344\2882534932.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(df[col].median(), inplace=True)
C:\Users\venka\AppData\Local\Temp\ipykernel_14344\2882534932.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(df[col].median(), inplace=True)
C:\Users\venka\AppData\Local\Temp\ipykernel_14344\2882534932.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(df[col].median(), inplace=True)
C:\Users\venka\AppData\Local\Temp\ipykernel_14344\2882534932.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(df[col].median(), inplace=True)

In [ ]:
df['seats'] = df['seats'].fillna(df['seats'].median())
df['seats'] = df['seats'].astype(int)

In [48]:
df['mileage'] = df['mileage'].fillna(df['mileage'].median())
df['engine'] = df['engine'].fillna(df['engine'].median())
df['max_power'] = df['max_power'].fillna(df['max_power'].median())

In [49]:
print(df.isnull().sum())
print(df.info())

Unnamed: 0           0
car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64
<class 'pandas.DataFrame'>
Index: 15503 entries, 0 to 15660
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         15503 non-null  int64
 1   car_name           15503 non-null  str
 2   brand              15503 non-null  str
 3   model              15503 non-null  str
 4   vehicle_age        15503 non-null  int64
 5   km_driven          15503 non-null  str
 6   seller_type        15503 non-null  str
 7   fuel_type          15503 non-null  str
 8   transmission_type  15503 non-null  str
 9   mileage            15503 non-null  float64
 10  engine             15503 non-null  float64
 11  max_power          15503 non-null  float64
 12  seats              15503 non-null  int64
 13  selling_price      15503 non-null  float64
dtypes: float64(4), int64(3), str(7)
memory usage: 1.8 MB
None

In [53]:
df = df.drop_duplicates()
df.shape

(15324, 14)

In [54]:
import numpy as np

# Step 1: Calculate mean selling price
mean_price = df['selling_price'].mean()

# Step 2: Create predictions (same value for all rows)
predictions = np.full(len(df), mean_price)

# Step 3: Calculate MAE
mae = np.mean(np.abs(df['selling_price'] - predictions))

print("Baseline Mean Price:", mean_price)
print("Baseline MAE:", mae)

Baseline Mean Price: 1036605.0555338032
Baseline MAE: 867382.2867031656